/**
 * AUTO-GENERATED by generate-env-config.mjs — do not edit by hand.
 * Source: .env + .env.example, overridden by process.env (e.g. Vercel) for PUBLIC keys. Re-run: npm run build
 * Public client config only (see PUBLIC_ENV_KEYS in generate-env-config.mjs). This file is loaded in the browser.
 */
window.GAPMAP_ENV = {
  SUPABASE_URL: "https://tjikcnsfaaqihgegecpi.supabase.co",
  SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqaWtjbnNmYWFxaWhnZWdlY3BpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY4MzQ4NjcsImV4cCI6MjA5MjQxMDg2N30.0m00pRwNDfTm_NhdkShI8-u6PAj_7p3o1xIH2lqrJOw",
  LICENSE_API_BASE: "http://localhost:3000",
  APP_DOWNLOAD_URL: "",
  APP_DEEP_LINK_URL: "",
  LEMONSQUEEZY_CHECKOUT_PRO: "",
  LEMONSQUEEZY_CHECKOUT_LIVE_PASS: "",
  LEMONSQUEEZY_CUSTOMER_PORTAL: "",
};
