#!/usr/bin/env bash
# Resume publishing after the Apple-portal cert-creation step.
#
# Prerequisite (manual, one-time, ~5 min):
#   1. https://developer.apple.com/account/resources/certificates/add
#   2. Pick 'Developer ID Application'
#   3. Upload .secrets/publishing/developer-id.csr (already generated)
#   4. Download the .cer Apple returns; save to:
#        .secrets/publishing/developer-id.cer
#   5. Run this script.
#
# This finishes everything else from CLI:
#   - Builds the .p12 from cert + key (openssl)
#   - Imports the .p12 into login keychain
#   - Picks the right Apple notarization mode (API key vs Apple-ID)
#   - Pushes every required GitHub Actions secret via `gh secret set`
#   - Prints next-step recipes (local smoke + tag push)
#
# Idempotent — re-running won't double-import or duplicate secrets.
set -euo pipefail

cd "$(dirname "$0")/.."
SECRETS_DIR=".secrets/publishing"
CERT="$SECRETS_DIR/developer-id.cer"
KEY="$SECRETS_DIR/developer-id.key"
P12="$SECRETS_DIR/developer-id.p12"
ENV_FILE=".env.publish"

# ─── 0. Preconditions ──────────────────────────────────────────────────
if [[ ! -f "$CERT" ]]; then
  echo "✗ $CERT not found." >&2
  echo "  Open https://developer.apple.com/account/resources/certificates/add" >&2
  echo "  → 'Developer ID Application' → upload $SECRETS_DIR/developer-id.csr" >&2
  echo "  → download the .cer Apple returns, save it as:" >&2
  echo "    $CERT" >&2
  echo "  Then re-run this script." >&2
  exit 1
fi
[[ -f "$KEY" ]] || { echo "✗ $KEY missing (was generated by 'asc certificates csr generate')" >&2; exit 1; }
[[ -f "$ENV_FILE" ]] || { echo "✗ $ENV_FILE missing (generated during publish-prep)" >&2; exit 1; }
# shellcheck disable=SC1090
source "$ENV_FILE"
: "${JWT_DESKTOP_SECRET:?JWT_DESKTOP_SECRET missing in $ENV_FILE}"
: "${APPLE_TEAM_ID:?APPLE_TEAM_ID missing in $ENV_FILE}"
: "${APPLE_SIGNING_IDENTITY:?APPLE_SIGNING_IDENTITY missing in $ENV_FILE}"

# ─── 1. Build .p12 ─────────────────────────────────────────────────────
# Apple returns a DER-encoded .cer; openssl needs to convert to PEM first.
echo "▶ Step 1/5 — Building .p12 from cert + private key"
P12_PASS="$(openssl rand -hex 16)"
PEM_TMP="$(mktemp /tmp/devid.XXXXXX.pem)"
trap 'rm -f "$PEM_TMP"' EXIT
openssl x509 -inform DER -in "$CERT" -out "$PEM_TMP"
openssl pkcs12 -export \
  -in "$PEM_TMP" \
  -inkey "$KEY" \
  -out "$P12" \
  -passout "pass:$P12_PASS" \
  -name "Developer ID Application: ${APPLE_SIGNING_IDENTITY##*: }" \
  -macalg sha256
chmod 600 "$P12"
echo "  ✓ $P12  (random password stored in $ENV_FILE)"

# Persist the .p12 password so the smoke-build can use it later.
if ! grep -q "^P12_PASSWORD=" "$ENV_FILE"; then
  echo "P12_PASSWORD=$P12_PASS" >> "$ENV_FILE"
else
  # Update in place — re-runs with a new .p12 password
  sed -i.bak "s|^P12_PASSWORD=.*|P12_PASSWORD=$P12_PASS|" "$ENV_FILE"
  rm -f "$ENV_FILE.bak"
fi

# ─── 2. Import into login keychain ─────────────────────────────────────
echo
echo "▶ Step 2/5 — Importing into login keychain"
if security find-identity -v -p codesigning | grep -q "Developer ID Application"; then
  echo "  ✓ already imported (security find-identity shows it)"
else
  security import "$P12" -k ~/Library/Keychains/login.keychain-db -P "$P12_PASS" -T /usr/bin/codesign -T /usr/bin/security
  security set-key-partition-list -S apple-tool:,apple: -k "" ~/Library/Keychains/login.keychain-db >/dev/null 2>&1 || true
  echo "  ✓ imported"
fi
security find-identity -v -p codesigning | grep -E "Developer ID|Apple Distribution|Apple Development" | head -5

# ─── 3. Resolve signing identity exact name ────────────────────────────
SIGNING_IDENTITY=$(security find-identity -v -p codesigning | grep 'Developer ID Application' | head -1 | sed 's/.*"\(.*\)".*/\1/')
if [[ -z "$SIGNING_IDENTITY" ]]; then
  echo "✗ Couldn't resolve 'Developer ID Application' identity in keychain. Aborting." >&2
  exit 1
fi
echo
echo "▶ Signing identity: $SIGNING_IDENTITY"

# ─── 4. Push GitHub Actions secrets via gh ─────────────────────────────
echo
echo "▶ Step 4/5 — Pushing secrets to GitHub Actions"
gh auth status >/dev/null 2>&1 || { echo "✗ gh CLI not authenticated. Run: gh auth login" >&2; exit 1; }

B64_P12="$(base64 < "$P12")"

set_secret() {
  local name="$1" value="$2"
  if [[ -z "$value" ]]; then
    echo "  ⊘ skipping $name (empty)"
    return
  fi
  printf '%s' "$value" | gh secret set "$name" --body - >/dev/null
  echo "  ✓ $name"
}

set_secret JWT_DESKTOP_SECRET         "$JWT_DESKTOP_SECRET"
set_secret APPLE_CERTIFICATE          "$B64_P12"
set_secret APPLE_CERTIFICATE_PASSWORD "$P12_PASS"
set_secret APPLE_SIGNING_IDENTITY     "$SIGNING_IDENTITY"
set_secret APPLE_TEAM_ID              "$APPLE_TEAM_ID"

# Notarization credentials (Option A — app-specific password)
if [[ -n "${APPLE_PASSWORD:-}" && -n "${APPLE_ID:-}" ]]; then
  set_secret APPLE_ID       "$APPLE_ID"
  set_secret APPLE_PASSWORD "$APPLE_PASSWORD"
  echo "  · Notarization mode: app-specific password"
else
  echo
  echo "  ⚠ APPLE_PASSWORD not set in $ENV_FILE — add an app-specific password"
  echo "    from https://appleid.apple.com (Sign-In and Security → App-Specific"
  echo "    Passwords) then re-run. Without it CI builds are signed but NOT"
  echo "    notarized; macOS Gatekeeper will warn on first launch."
fi

# ─── 5. Show what's next ───────────────────────────────────────────────
echo
echo "🎉 GitHub Actions is ready. Final pre-tag smoke test:"
echo
echo "   source .env.publish"
echo "   export JWT_DESKTOP_SECRET APPLE_SIGNING_IDENTITY APPLE_TEAM_ID APPLE_ID APPLE_PASSWORD"
echo "   scripts/publish-mac.sh --arch arm64 --sign"
echo
echo "   # Inspect the DMG:"
echo '   codesign -vvv --deep --strict "app-tauri/src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/"*.dmg'
echo '   spctl -a -vv                  "app-tauri/src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/"*.dmg'
echo
echo "When the local DMG passes both checks, ship via CI:"
echo
echo "   git tag v0.1.0"
echo "   git push origin v0.1.0"
echo
echo "release.yml will build arm64 + x86_64 DMGs, sign + notarize, and upload"
echo "to a draft release at https://github.com/USER/reddit-myind/releases."
