/* Waiting-list signup for the OpenReply homepage.
 *
 * Stores emails in the Supabase `waiting_list` table. You must create the
 * table and allow anonymous inserts:
 *
 *   create table waiting_list (
 *     id uuid default gen_random_uuid() primary key,
 *     email text not null unique,
 *     source text default 'homepage',
 *     created_at timestamptz default now()
 *   );
 *   alter table waiting_list enable row level security;
 *   create policy "Allow anonymous inserts" on waiting_list
 *     for insert to anon with check (true);
 *
 * Env vars are injected via env.config.js (generated by generate-env-config.mjs
 * from .env at build time).
 */
(function () {
  function getEnv() {
    const e = window.OPENREPLY_ENV || {};
    return {
      url: e.SUPABASE_URL || e.NEXT_PUBLIC_SUPABASE_URL || "",
      key: e.SUPABASE_ANON_KEY || e.NEXT_PUBLIC_SUPABASE_ANON_KEY || "",
    };
  }

  async function joinWaitingList(email) {
    const { url, key } = getEnv();
    if (!url || !key) {
      throw new Error("Supabase is not configured for this build.");
    }
    if (!window.supabase || !window.supabase.createClient) {
      throw new Error("Supabase SDK failed to load.");
    }
    const sb = window.supabase.createClient(url, key);
    const { error } = await sb
      .from("waiting_list")
      .insert([{ email: email.toLowerCase().trim(), source: "homepage" }]);
    if (error) throw error;
    return true;
  }

  document.addEventListener("DOMContentLoaded", function () {
    const form = document.getElementById("wl-form");
    const input = document.getElementById("wl-email");
    const msg = document.getElementById("wl-msg");
    if (!form || !input || !msg) return;

    form.addEventListener("submit", async function (e) {
      e.preventDefault();
      const email = input.value.trim();
      if (!email || !input.checkValidity()) {
        msg.textContent = "Please enter a valid email address.";
        msg.className = "wl-msg error";
        return;
      }

      const btn = form.querySelector("button[type='submit']");
      const originalText = btn.textContent;
      btn.disabled = true;
      btn.textContent = "Joining…";
      msg.textContent = "";
      msg.className = "wl-msg";

      try {
        await joinWaitingList(email);
        form.reset();
        msg.textContent = "✓ You're on the list. We'll email you when cloud sign-ups open.";
        msg.className = "wl-msg success";
      } catch (err) {
        const text = err?.message || String(err || "Unknown error");
        msg.textContent = "Could not join: " + text;
        msg.className = "wl-msg error";
      } finally {
        btn.disabled = false;
        btn.textContent = originalText;
      }
    });
  });
})();
